name: Deploy Hugo

on:
  push:
    branches: [ "main" ]  # 当 main 分支有推送时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码和子模块（确保主题加载）
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 关键！确保拉取主题子模块

      # 2. 安装指定版本的 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.1'  # 必须与你的本地版本一致
          extended: true

      # 3. 构建静态网站并清理旧文件
      - name: Build
        run: hugo --minify --gc --cleanDestinationDir

      # 4. 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./public
